package API;

public enum Endpoint {
    GET_ALLTASKS,
    GET_TASKS,
    GET_TASK,
    GET_EPIC,
    GET_EPICS,
    GET_SUBTASK,
    GET_HISTORY,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    DELETE_ALLTASKS,
    DELETE_TASKS,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_ALLSUBTASKS,
    GET_SUBTASKS,
    DELETE_SUBTASK,
    DELETE_ALLEPICS,
    GET_PRIORITIZE,
    GET_EPICSUBTASK,
    UNKNOWN
}
